export const TOGGLE_CURSOR_COLOR = 'TOGGLE_CURSOR_COLOR';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const SUBMIT = 'SUBMIT';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const CLEAN_CHARACTERS = 'CLEAN_CHARACTERS';
export const MOVE_CURSOR_RIGHT = 'MOVE_CURSOR_RIGHT';
export const MOVE_CURSOR_LEFT = 'MOVE_CURSOR_LEFT';
export const PROGRAM_NOT_FOUND = 'PROGRAM_NOT_FOUND';
export const RESURRECT_LAST_COMMAND_BACKWARDS =
  'RESURRECT_LAST_COMMAND_BACKWARDS';
export const RESURRECT_LAST_COMMAND_FORWARDS =
  'RESURRECT_LAST_COMMAND_FORWARDS';
export const ADD_TO_OUTPUT = 'ADD_TO_OUTPUT';
